// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZTgfOcXu4_oGDCv2JxnA6n7zMCeA6e4I',
    appId: '1:653068813317:web:0c553ab44e00ce3f8ac86c',
    messagingSenderId: '653068813317',
    projectId: 'seladata-app',
    authDomain: 'seladata-app.firebaseapp.com',
    storageBucket: 'seladata-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_uNGPf98VaNxEjp9jJx_zWToIiBiDpuE',
    appId: '1:653068813317:android:ee0a31edf26d130c8ac86c',
    messagingSenderId: '653068813317',
    projectId: 'seladata-app',
    storageBucket: 'seladata-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFIz5S1zN4OoBvdKfoHpPwb1KmIrkdfU4',
    appId: '1:653068813317:ios:bb566a0dd6ac5e618ac86c',
    messagingSenderId: '653068813317',
    projectId: 'seladata-app',
    storageBucket: 'seladata-app.firebasestorage.app',
    iosBundleId: 'com.example.seladata',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFIz5S1zN4OoBvdKfoHpPwb1KmIrkdfU4',
    appId: '1:653068813317:ios:bb566a0dd6ac5e618ac86c',
    messagingSenderId: '653068813317',
    projectId: 'seladata-app',
    storageBucket: 'seladata-app.firebasestorage.app',
    iosBundleId: 'com.example.seladata',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZTgfOcXu4_oGDCv2JxnA6n7zMCeA6e4I',
    appId: '1:653068813317:web:03c0b2fc97ea70648ac86c',
    messagingSenderId: '653068813317',
    projectId: 'seladata-app',
    authDomain: 'seladata-app.firebaseapp.com',
    storageBucket: 'seladata-app.firebasestorage.app',
  );
}
